export type {
  Capability,
  CapabilityId,
  Goal,
  GoalId,
  GoalPriority,
} from './goals/goal.types';
export { CAPABILITY_IDS, GOAL_IDS } from './goals/goal.types';

export type {
  EquipmentId,
  EquipmentRequirement,
  Exercise,
  ExerciseId,
  ExerciseMeasurement,
  ExerciseModality,
  ExerciseRisk,
  ExerciseRiskLevel,
  MuscleGroup,
  MuscleTarget,
} from './exercises/exercise.types';
export { EQUIPMENT_IDS, MUSCLE_GROUPS, RISK_LEVELS } from './exercises/exercise.types';
export type { Project45Exercise } from './exercises/catalog';
export { PROJECT45_EXERCISES } from './exercises/catalog';

export type {
  AggregateId,
  Event,
  EventId,
  EventMetadata,
  EventVersion,
  ExerciseCompleted,
  GoalChanged,
  GtoTestRecorded,
  Project45Event,
  RecoveryRecorded,
  WeightRecorded,
  WorkoutCompleted,
  WorkoutStarted,
} from './events';

export type {
  BlockType,
  ExercisePrescription,
  LocationType,
  PrescriptionIntensity,
  SessionType,
  TrainingDay,
  TrainingDayId,
  WorkoutBlock,
  WorkoutBlockId,
  WorkoutLifecycleFailure,
  WorkoutLifecycleResult,
  WorkoutLifecycleState,
  WorkoutLifecycleSuccess,
  WorkoutLifecycleTransition,
  WorkoutPlan,
  WorkoutPlanId,
  WorkoutSession,
  WorkoutSessionId,
} from './workouts';
export type {
  ConstraintEvaluationInput,
  ConstraintOutcome,
  ConstraintResult,
  Planner,
  PlanningConstraint,
  PlanningConstraints,
  PlanningContext,
  PlanningRecoveryData,
  PlanningRule,
  PlanningRuleInput,
  Project45WeeklySeedPlan,
  RecoveryReadiness,
  PlanScore,
  ScoreByDimension,
  ScoreDimension,
  ScoreExplanation,
  RuleOutcome,
  RuleResult,
  RuleSeverity,
  WorkoutScore,
  WorkoutScoringOptions,
} from './workouts';
export {
  BLOCK_TYPES,
  LOCATION_TYPES,
  PROJECT45_WEEKLY_SEED_PLAN,
  SESSION_TYPES,
  WORKOUT_LIFECYCLE_STATES,
  WORKOUT_LIFECYCLE_TRANSITIONS,
  complete,
  evaluatePlanningConstraint,
  STARTER_PLANNING_RULES,
  avoidBackToBackHardRunningDaysRule,
  avoidHeavyLowerBodyAfterRunningIntervalsRule,
  coreActivationBeforeAbWheelRule,
  ensureWeeklyRecoveryDayRule,
  flagPoorRecoveryRule,
  pause,
  planProject45Week,
  project45SeedPlanner,
  resume,
  resolveExerciseSubstitutions,
  runPlanningRules,
  SCORE_DIMENSIONS,
  scoreTrainingDay,
  scoreWorkoutPlan,
  scoreWorkoutSession,
  skip,
  start,
} from './workouts';
