import type { Exercise, ExerciseId } from './exercise.types';

const exerciseId = (value: string): ExerciseId => value as ExerciseId;

export const PROJECT45_EXERCISES = [
  {
    id: exerciseId('goblet-squat'),
    name: 'Goblet Squat',
    summary: 'Front-loaded squat pattern for lower-body strength and trunk position.',
    modality: 'strength',
    goals: ['gto_gold', 'hyperlordosis'],
    capabilities: ['strength', 'core', 'posture'],
    equipment: { required: ['dumbbells'], optional: ['floor_mat'] },
    muscleGroups: { primary: ['quads', 'glutes'], secondary: ['core'] },
    measurements: ['reps', 'load'],
    risk: { level: 'medium', notes: ['Keep ribs stacked over pelvis and avoid lumbar extension.'] },
    instructions: ['Hold one dumbbell at chest height.', 'Squat to a controlled depth.', 'Stand tall without leaning back.'],
    coachingCues: ['Tripod foot.', 'Knees track over toes.', 'Exhale through the sticking point.'],
  },
  {
    id: exerciseId('romanian-deadlift'),
    name: 'Romanian Deadlift',
    summary: 'Hip hinge for posterior-chain strength and hamstring control.',
    modality: 'strength',
    goals: ['gto_gold', 'hyperlordosis'],
    capabilities: ['strength', 'posture'],
    equipment: { required: ['dumbbells'] },
    muscleGroups: { primary: ['hamstrings', 'glutes'], secondary: ['back', 'core'] },
    measurements: ['reps', 'load'],
    risk: { level: 'medium', notes: ['Stop range when pelvis or spine position changes.'] },
    instructions: ['Stand tall with weights at the thighs.', 'Hinge hips back with soft knees.', 'Drive hips forward to stand.'],
    coachingCues: ['Long spine.', 'Hips back, not down.', 'Weights stay close.'],
  },
  {
    id: exerciseId('step-up'),
    name: 'Step-Up',
    summary: 'Single-leg strength pattern for climbing, hiking, and GTO preparation.',
    modality: 'strength',
    goals: ['gto_gold', 'hiking', 'endurance'],
    capabilities: ['strength', 'endurance'],
    equipment: { required: ['gym_bench'], optional: ['dumbbells'] },
    muscleGroups: { primary: ['quads', 'glutes'], secondary: ['calves', 'core'] },
    measurements: ['reps', 'load'],
    risk: { level: 'medium', notes: ['Use a stable step height that allows full foot contact.'] },
    instructions: ['Place one foot fully on the step.', 'Drive through the lead leg.', 'Lower under control.'],
    coachingCues: ['Quiet landing.', 'Tall chest.', 'Lead knee tracks forward.'],
  },
  {
    id: exerciseId('walking-lunge'),
    name: 'Walking Lunge',
    summary: 'Alternating lunge for lower-body capacity and gait control.',
    modality: 'strength',
    goals: ['gto_gold', 'endurance'],
    capabilities: ['strength', 'endurance', 'posture'],
    equipment: { required: ['bodyweight'], optional: ['dumbbells'] },
    muscleGroups: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'core'] },
    measurements: ['reps', 'load'],
    risk: { level: 'medium', notes: ['Shorten stride if the low back arches or balance breaks.'] },
    instructions: ['Step forward into a lunge.', 'Push through the front foot.', 'Alternate legs with control.'],
    coachingCues: ['Ribs down.', 'Slow descent.', 'Push the floor away.'],
  },
  {
    id: exerciseId('push-up'),
    name: 'Push-Up',
    summary: 'Horizontal pushing pattern with full-body bracing.',
    modality: 'strength',
    goals: ['gto_gold', 'core_strength'],
    capabilities: ['strength', 'core'],
    equipment: { required: ['bodyweight'] },
    muscleGroups: { primary: ['chest', 'arms'], secondary: ['shoulders', 'core'] },
    measurements: ['reps'],
    risk: { level: 'medium', notes: ['Elevate hands if plank position cannot be maintained.'] },
    instructions: ['Start in a strong plank.', 'Lower chest toward the floor.', 'Press back to the start position.'],
    coachingCues: ['Straight line head to heels.', 'Elbows about 45 degrees.', 'Brace before each rep.'],
  },
  {
    id: exerciseId('lat-pulldown'),
    name: 'Lat Pulldown',
    summary: 'Vertical pulling pattern for upper-body strength and posture.',
    modality: 'strength',
    goals: ['gto_gold', 'climbing'],
    capabilities: ['strength', 'posture', 'grip'],
    equipment: { required: ['lat_pulldown'] },
    muscleGroups: { primary: ['back'], secondary: ['arms', 'shoulders'] },
    measurements: ['reps', 'load'],
    risk: { level: 'low' },
    instructions: ['Grip the bar slightly wider than shoulders.', 'Pull elbows down toward ribs.', 'Return with control.'],
    coachingCues: ['Chest tall.', 'Shoulders away from ears.', 'Lead with elbows.'],
  },
  {
    id: exerciseId('seated-row'),
    name: 'Seated Row',
    summary: 'Horizontal pulling pattern for back strength and shoulder control.',
    modality: 'strength',
    goals: ['gto_gold', 'climbing'],
    capabilities: ['strength', 'posture', 'grip'],
    equipment: { required: ['cable_machine'] },
    muscleGroups: { primary: ['back'], secondary: ['arms', 'shoulders'] },
    measurements: ['reps', 'load'],
    risk: { level: 'low' },
    instructions: ['Sit tall with arms extended.', 'Row handles toward ribs.', 'Return without rounding forward.'],
    coachingCues: ['Tall spine.', 'Pull shoulder blades back and down.', 'Pause at the ribs.'],
  },
  {
    id: exerciseId('farmers-walk'),
    name: "Farmer's Walk",
    summary: 'Loaded carry for grip, trunk stiffness, and work capacity.',
    modality: 'strength',
    goals: ['gto_gold', 'endurance', 'hiking'],
    capabilities: ['strength', 'core', 'grip', 'endurance'],
    equipment: { required: ['dumbbells'] },
    muscleGroups: { primary: ['core', 'arms'], secondary: ['shoulders', 'back', 'glutes'] },
    measurements: ['distance', 'time', 'load'],
    risk: { level: 'medium', notes: ['Use a load that does not change posture or gait.'] },
    instructions: ['Pick up weights from a strong hinge.', 'Walk with small controlled steps.', 'Set weights down with control.'],
    coachingCues: ['Tall posture.', 'Quiet steps.', 'Do not lean side to side.'],
  },
  {
    id: exerciseId('plank'),
    name: 'Plank',
    summary: 'Static anterior-core brace for trunk endurance.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis', 'pelvic_floor'],
    capabilities: ['core', 'posture', 'pelvic_control'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['glutes', 'shoulders'] },
    measurements: ['time'],
    risk: { level: 'low', notes: ['Stop before low-back sagging starts.'] },
    instructions: ['Set elbows under shoulders.', 'Extend legs into a straight line.', 'Hold while breathing steadily.'],
    coachingCues: ['Ribs down.', 'Squeeze glutes lightly.', 'Push floor away.'],
  },
  {
    id: exerciseId('side-plank'),
    name: 'Side Plank',
    summary: 'Lateral-core endurance drill for pelvic and trunk control.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis'],
    capabilities: ['core', 'posture'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['glutes', 'shoulders'] },
    measurements: ['time'],
    risk: { level: 'low' },
    instructions: ['Set elbow under shoulder.', 'Stack feet or stagger them.', 'Lift hips and hold a long line.'],
    coachingCues: ['Hips forward.', 'Neck long.', 'Breathe behind the brace.'],
  },
  {
    id: exerciseId('dead-bug'),
    name: 'Dead Bug',
    summary: 'Supine core drill for rib-pelvis stacking and limb control.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis', 'pelvic_floor'],
    capabilities: ['core', 'posture', 'pelvic_control'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['hip_flexors'] },
    measurements: ['reps'],
    risk: { level: 'low' },
    instructions: ['Lie on your back with hips and knees at 90 degrees.', 'Reach opposite arm and leg away.', 'Return without arching the low back.'],
    coachingCues: ['Exhale first.', 'Low ribs heavy.', 'Move slowly.'],
  },
  {
    id: exerciseId('glute-bridge'),
    name: 'Glute Bridge',
    summary: 'Hip extension drill for glute strength and pelvic position.',
    modality: 'strength',
    goals: ['hyperlordosis', 'pelvic_floor', 'core_strength'],
    capabilities: ['strength', 'posture', 'pelvic_control'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['glutes'], secondary: ['hamstrings', 'core'] },
    measurements: ['reps'],
    risk: { level: 'low' },
    instructions: ['Lie on your back with knees bent.', 'Press through heels and lift hips.', 'Lower with control.'],
    coachingCues: ['Ribs stay down.', 'Finish with glutes, not low back.', 'Exhale at the top.'],
  },
  {
    id: exerciseId('pallof-press'),
    name: 'Pallof Press',
    summary: 'Anti-rotation core drill for trunk control and posture.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis'],
    capabilities: ['core', 'posture'],
    equipment: { required: ['cable_machine'], optional: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['glutes', 'shoulders'] },
    measurements: ['reps', 'load'],
    risk: { level: 'low' },
    instructions: ['Stand side-on to the cable.', 'Press handles straight out.', 'Return without rotating.'],
    coachingCues: ['Level pelvis.', 'Slow press.', 'Resist the pull.'],
  },
  {
    id: exerciseId('pelvic-floor-breathing'),
    name: 'Pelvic Floor Breathing',
    summary: 'Breathing reset for pelvic floor awareness and down-regulation.',
    modality: 'recovery',
    goals: ['pelvic_floor', 'relief'],
    capabilities: ['pelvic_control', 'recovery'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['pelvic_floor'], secondary: ['core'] },
    measurements: ['time'],
    risk: { level: 'low', notes: ['Use gentle effort and avoid breath holding.'] },
    instructions: ['Lie comfortably with knees supported.', 'Inhale into the lower ribs and pelvis.', 'Exhale slowly and relax tension.'],
    coachingCues: ['Gentle breath.', 'Jaw relaxed.', 'Let the floor soften on inhale.'],
  },
  {
    id: exerciseId('heel-slide'),
    name: 'Heel Slide',
    summary: 'Low-load core and pelvic control drill for limb movement without extension.',
    modality: 'mobility',
    goals: ['pelvic_floor', 'hyperlordosis', 'core_strength'],
    capabilities: ['core', 'pelvic_control', 'posture'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['hip_flexors', 'pelvic_floor'] },
    measurements: ['reps'],
    risk: { level: 'low' },
    instructions: ['Lie on your back with knees bent.', 'Slide one heel away slowly.', 'Return without the pelvis tipping.'],
    coachingCues: ['Quiet pelvis.', 'Exhale as the leg moves.', 'Small range is fine.'],
  },
  {
    id: exerciseId('incline-treadmill-walk'),
    name: 'Incline Treadmill Walk',
    summary: 'Low-impact endurance work for aerobic capacity and hiking preparation.',
    modality: 'cardio',
    goals: ['endurance', 'hiking', 'gto_gold'],
    capabilities: ['endurance', 'recovery'],
    equipment: { required: ['treadmill'] },
    muscleGroups: { primary: ['calves', 'glutes'], secondary: ['quads', 'hamstrings'] },
    measurements: ['time', 'distance'],
    risk: { level: 'low', notes: ['Use an incline and pace that allow steady nasal or conversational breathing.'] },
    instructions: ['Set a moderate incline.', 'Walk at a sustainable pace.', 'Cool down gradually.'],
    coachingCues: ['Tall posture.', 'Short quick steps.', 'Relax shoulders.'],
  },
  {
    id: exerciseId('zone-2-walk'),
    name: 'Zone 2 Walk',
    summary: 'Easy aerobic session for endurance and recovery base building.',
    modality: 'cardio',
    goals: ['endurance', 'relief'],
    capabilities: ['endurance', 'recovery'],
    equipment: { required: ['outdoor'] },
    muscleGroups: { primary: ['calves', 'glutes'], secondary: ['quads', 'hamstrings'] },
    measurements: ['time', 'distance'],
    risk: { level: 'low' },
    instructions: ['Choose an easy route.', 'Walk at a pace you can maintain comfortably.', 'Finish feeling better than when you started.'],
    coachingCues: ['Nasal or conversational pace.', 'Light arms.', 'Even stride.'],
  },
  {
    id: exerciseId('kettlebell-swing'),
    name: 'Kettlebell Swing',
    summary: 'Dynamic hinge for power, conditioning, and posterior-chain capacity.',
    modality: 'strength',
    goals: ['gto_gold', 'endurance'],
    capabilities: ['strength', 'endurance'],
    equipment: { required: ['dumbbells'] },
    muscleGroups: { primary: ['glutes', 'hamstrings'], secondary: ['core', 'back'] },
    measurements: ['reps', 'load'],
    risk: {
      level: 'high',
      notes: ['Use only after hinge mechanics are reliable.'],
      contraindications: ['Avoid if ballistic hinging irritates the back or pelvic floor symptoms.'],
    },
    instructions: ['Hike the weight back between the hips.', 'Snap hips forward to float the weight.', 'Let the weight return into the hinge.'],
    coachingCues: ['Hinge, do not squat.', 'Arms are hooks.', 'Finish tall without leaning back.'],
  },
] as const satisfies readonly Exercise[];

export type Project45Exercise = (typeof PROJECT45_EXERCISES)[number];
