import type { Exercise, ExerciseId } from './exercise.types';

const exerciseId = (value: string): ExerciseId => value as ExerciseId;

export const PROJECT45_EXERCISES: readonly Exercise[] = [
  {
    id: exerciseId('goblet-squat'),
    name: 'Goblet Squat',
    summary: 'Front-loaded squat pattern for lower-body strength and trunk position.',
    shortInstruction: 'Hold the weight at your chest, squat under control, then stand tall without leaning back.',
    modality: 'strength',
    goals: ['gto_gold', 'hyperlordosis'],
    capabilities: ['strength', 'core', 'posture'],
    equipment: { required: ['dumbbells'], optional: ['floor_mat'] },
    muscleGroups: { primary: ['quads', 'glutes'], secondary: ['core'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/goblet-squat.gif', alt: 'Goblet squat demonstration', source: 'Legacy app GIF' },
    risk: { level: 'medium', notes: ['Keep ribs stacked over pelvis and avoid lumbar extension.'] },
    instructions: ['Hold one dumbbell at chest height.', 'Squat to a controlled depth.', 'Stand tall without leaning back.'],
    commonMistakes: ['Leaning back at the top.', 'Letting knees collapse inward.', 'Dropping into the bottom position.'],
    coachingCues: ['Tripod foot.', 'Knees track over toes.', 'Exhale through the sticking point.'],
  },
  {
    id: exerciseId('romanian-deadlift'),
    name: 'Romanian Deadlift',
    summary: 'Hip hinge for posterior-chain strength and hamstring control.',
    shortInstruction: 'Push hips back with a long spine, keep the weights close, then drive hips forward to stand.',
    modality: 'strength',
    goals: ['gto_gold', 'hyperlordosis'],
    capabilities: ['strength', 'posture'],
    equipment: { required: ['dumbbells'] },
    muscleGroups: { primary: ['hamstrings', 'glutes'], secondary: ['back', 'core'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/romanian-deadlift.gif', alt: 'Romanian deadlift demonstration', source: 'Legacy app GIF' },
    risk: { level: 'medium', notes: ['Stop range when pelvis or spine position changes.'] },
    instructions: ['Stand tall with weights at the thighs.', 'Hinge hips back with soft knees.', 'Drive hips forward to stand.'],
    commonMistakes: ['Squatting instead of hinging.', 'Letting weights drift away from the legs.', 'Rounding or over-arching the back.'],
    coachingCues: ['Long spine.', 'Hips back, not down.', 'Weights stay close.'],
  },
  {
    id: exerciseId('step-up'),
    name: 'Step-Up',
    summary: 'Single-leg strength pattern for climbing, hiking, and GTO preparation.',
    shortInstruction: 'Put the whole foot on the step, drive through the lead leg, and lower with control.',
    modality: 'strength',
    goals: ['gto_gold', 'hiking', 'endurance'],
    capabilities: ['strength', 'endurance'],
    equipment: { required: ['gym_bench'], optional: ['dumbbells'] },
    muscleGroups: { primary: ['quads', 'glutes'], secondary: ['calves', 'core'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/step-up.gif', alt: 'Step-up demonstration', source: 'Legacy app GIF' },
    risk: { level: 'medium', notes: ['Use a stable step height that allows full foot contact.'] },
    instructions: ['Place one foot fully on the step.', 'Drive through the lead leg.', 'Lower under control.'],
    commonMistakes: ['Pushing mostly from the trailing leg.', 'Letting the lead knee cave inward.', 'Dropping quickly back to the floor.'],
    coachingCues: ['Quiet landing.', 'Tall chest.', 'Lead knee tracks forward.'],
  },
  {
    id: exerciseId('walking-lunge'),
    name: 'Walking Lunge',
    summary: 'Alternating lunge for lower-body capacity and gait control.',
    shortInstruction: 'Step forward, lower slowly, then push through the front foot and alternate legs.',
    modality: 'strength',
    goals: ['gto_gold', 'endurance'],
    capabilities: ['strength', 'endurance', 'posture'],
    equipment: { required: ['bodyweight'], optional: ['dumbbells'] },
    muscleGroups: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'core'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/walking-lunge.gif', alt: 'Walking lunge demonstration', source: 'Legacy app GIF' },
    risk: { level: 'medium', notes: ['Shorten stride if the low back arches or balance breaks.'] },
    instructions: ['Step forward into a lunge.', 'Push through the front foot.', 'Alternate legs with control.'],
    commonMistakes: ['Taking a stride that is too long.', 'Losing rib and pelvis position.', 'Bouncing out of the bottom.'],
    coachingCues: ['Ribs down.', 'Slow descent.', 'Push the floor away.'],
  },
  {
    id: exerciseId('push-up'),
    name: 'Push-Up',
    summary: 'Horizontal pushing pattern with full-body bracing.',
    shortInstruction: 'Start in a strong plank, lower the chest under control, and press back up as one piece.',
    modality: 'strength',
    goals: ['gto_gold', 'core_strength'],
    capabilities: ['strength', 'core'],
    equipment: { required: ['bodyweight'] },
    muscleGroups: { primary: ['chest', 'arms'], secondary: ['shoulders', 'core'] },
    measurements: ['reps'],
    media: { kind: 'gif', path: '../gifs/push-up.gif', alt: 'Push-up demonstration', source: 'Legacy app GIF' },
    risk: { level: 'medium', notes: ['Elevate hands if plank position cannot be maintained.'] },
    instructions: ['Start in a strong plank.', 'Lower chest toward the floor.', 'Press back to the start position.'],
    commonMistakes: ['Sagging the hips.', 'Flaring elbows straight out.', 'Reaching the head forward.'],
    coachingCues: ['Straight line head to heels.', 'Elbows about 45 degrees.', 'Brace before each rep.'],
  },
  {
    id: exerciseId('lat-pulldown'),
    name: 'Lat Pulldown',
    summary: 'Vertical pulling pattern for upper-body strength and posture.',
    shortInstruction: 'Sit tall, pull elbows down toward your ribs, then return the bar with control.',
    modality: 'strength',
    goals: ['gto_gold', 'climbing'],
    capabilities: ['strength', 'posture', 'grip'],
    equipment: { required: ['lat_pulldown'] },
    muscleGroups: { primary: ['back'], secondary: ['arms', 'shoulders'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/lat-pulldown.gif', alt: 'Lat pulldown demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low' },
    instructions: ['Grip the bar slightly wider than shoulders.', 'Pull elbows down toward ribs.', 'Return with control.'],
    commonMistakes: ['Shrugging shoulders up.', 'Leaning far back to move the weight.', 'Letting the bar snap upward.'],
    coachingCues: ['Chest tall.', 'Shoulders away from ears.', 'Lead with elbows.'],
  },
  {
    id: exerciseId('seated-row'),
    name: 'Seated Row',
    summary: 'Horizontal pulling pattern for back strength and shoulder control.',
    shortInstruction: 'Sit tall, row handles to your ribs, and return without rounding forward.',
    modality: 'strength',
    goals: ['gto_gold', 'climbing'],
    capabilities: ['strength', 'posture', 'grip'],
    equipment: { required: ['cable_machine'] },
    muscleGroups: { primary: ['back'], secondary: ['arms', 'shoulders'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/seated-row.gif', alt: 'Seated row demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low' },
    instructions: ['Sit tall with arms extended.', 'Row handles toward ribs.', 'Return without rounding forward.'],
    commonMistakes: ['Yanking with the low back.', 'Shrugging at the finish.', 'Rounding forward between reps.'],
    coachingCues: ['Tall spine.', 'Pull shoulder blades back and down.', 'Pause at the ribs.'],
  },
  {
    id: exerciseId('farmers-walk'),
    name: "Farmer's Walk",
    summary: 'Loaded carry for grip, trunk stiffness, and work capacity.',
    shortInstruction: 'Pick up the weights from a hinge, walk tall with quiet steps, and set them down under control.',
    modality: 'strength',
    goals: ['gto_gold', 'endurance', 'hiking'],
    capabilities: ['strength', 'core', 'grip', 'endurance'],
    equipment: { required: ['dumbbells'] },
    muscleGroups: { primary: ['core', 'arms'], secondary: ['shoulders', 'back', 'glutes'] },
    measurements: ['distance', 'time', 'load'],
    media: { kind: 'gif', path: '../gifs/farmers-walk.gif', alt: "Farmer's walk demonstration", source: 'Legacy app GIF' },
    risk: { level: 'medium', notes: ['Use a load that does not change posture or gait.'] },
    instructions: ['Pick up weights from a strong hinge.', 'Walk with small controlled steps.', 'Set weights down with control.'],
    commonMistakes: ['Leaning side to side.', 'Taking rushed uneven steps.', 'Dropping the weights carelessly.'],
    coachingCues: ['Tall posture.', 'Quiet steps.', 'Do not lean side to side.'],
  },
  {
    id: exerciseId('plank'),
    name: 'Plank',
    summary: 'Static anterior-core brace for trunk endurance.',
    shortInstruction: 'Set elbows under shoulders, make a straight line, and hold while breathing steadily.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis', 'pelvic_floor'],
    capabilities: ['core', 'posture', 'pelvic_control'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['glutes', 'shoulders'] },
    measurements: ['time'],
    media: { kind: 'gif', path: '../gifs/plank.gif', alt: 'Plank demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low', notes: ['Stop before low-back sagging starts.'] },
    instructions: ['Set elbows under shoulders.', 'Extend legs into a straight line.', 'Hold while breathing steadily.'],
    commonMistakes: ['Letting the low back sag.', 'Holding the breath.', 'Shrugging shoulders into the ears.'],
    coachingCues: ['Ribs down.', 'Squeeze glutes lightly.', 'Push floor away.'],
  },
  {
    id: exerciseId('side-plank'),
    name: 'Side Plank',
    summary: 'Lateral-core endurance drill for pelvic and trunk control.',
    shortInstruction: 'Stack or stagger the feet, lift hips, and hold a long line from head to heels.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis'],
    capabilities: ['core', 'posture'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['glutes', 'shoulders'] },
    measurements: ['time'],
    media: { kind: 'gif', path: '../gifs/side-plank.gif', alt: 'Side plank demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low' },
    instructions: ['Set elbow under shoulder.', 'Stack feet or stagger them.', 'Lift hips and hold a long line.'],
    commonMistakes: ['Letting hips drift backward.', 'Collapsing into the shoulder.', 'Holding the breath.'],
    coachingCues: ['Hips forward.', 'Neck long.', 'Breathe behind the brace.'],
  },
  {
    id: exerciseId('dead-bug'),
    name: 'Dead Bug',
    summary: 'Supine core drill for rib-pelvis stacking and limb control.',
    shortInstruction: 'Move opposite arm and leg slowly while keeping your low ribs and pelvis quiet.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis', 'pelvic_floor'],
    capabilities: ['core', 'posture', 'pelvic_control'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['hip_flexors'] },
    measurements: ['reps'],
    media: { kind: 'gif', path: '../gifs/dead-bug.gif', alt: 'Dead bug demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low' },
    instructions: ['Lie on your back with hips and knees at 90 degrees.', 'Reach opposite arm and leg away.', 'Return without arching the low back.'],
    commonMistakes: ['Arching the low back.', 'Moving too quickly.', 'Losing the exhale before the reach.'],
    coachingCues: ['Exhale first.', 'Low ribs heavy.', 'Move slowly.'],
  },
  {
    id: exerciseId('glute-bridge'),
    name: 'Glute Bridge',
    summary: 'Hip extension drill for glute strength and pelvic position.',
    shortInstruction: 'Press through your heels, lift hips with glutes, and lower without arching your back.',
    modality: 'strength',
    goals: ['hyperlordosis', 'pelvic_floor', 'core_strength'],
    capabilities: ['strength', 'posture', 'pelvic_control'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['glutes'], secondary: ['hamstrings', 'core'] },
    measurements: ['reps'],
    media: { kind: 'gif', path: '../gifs/glute-bridge.gif', alt: 'Glute bridge demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low' },
    instructions: ['Lie on your back with knees bent.', 'Press through heels and lift hips.', 'Lower with control.'],
    commonMistakes: ['Over-arching at the top.', 'Pushing through the toes.', 'Letting knees fall inward.'],
    coachingCues: ['Ribs stay down.', 'Finish with glutes, not low back.', 'Exhale at the top.'],
  },
  {
    id: exerciseId('pallof-press'),
    name: 'Pallof Press',
    summary: 'Anti-rotation core drill for trunk control and posture.',
    shortInstruction: 'Stand side-on to the cable, press straight out, and resist rotation.',
    modality: 'strength',
    goals: ['core_strength', 'hyperlordosis'],
    capabilities: ['core', 'posture'],
    equipment: { required: ['cable_machine'], optional: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['glutes', 'shoulders'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/pallof-press.gif', alt: 'Pallof press demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low' },
    instructions: ['Stand side-on to the cable.', 'Press handles straight out.', 'Return without rotating.'],
    commonMistakes: ['Rotating toward the cable.', 'Shrugging shoulders.', 'Using too much load to control.'],
    coachingCues: ['Level pelvis.', 'Slow press.', 'Resist the pull.'],
  },
  {
    id: exerciseId('pelvic-floor-breathing'),
    name: 'Pelvic Floor Breathing',
    summary: 'Breathing reset for pelvic floor awareness and down-regulation.',
    shortInstruction: 'Breathe gently into the lower ribs and pelvis, then exhale slowly and let tension soften.',
    modality: 'recovery',
    goals: ['pelvic_floor', 'relief'],
    capabilities: ['pelvic_control', 'recovery'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['pelvic_floor'], secondary: ['core'] },
    measurements: ['time'],
    risk: { level: 'low', notes: ['Use gentle effort and avoid breath holding.'] },
    instructions: ['Lie comfortably with knees supported.', 'Inhale into the lower ribs and pelvis.', 'Exhale slowly and relax tension.'],
    commonMistakes: ['Forcing the breath.', 'Clenching on the inhale.', 'Trying to make the exercise feel intense.'],
    coachingCues: ['Gentle breath.', 'Jaw relaxed.', 'Let the floor soften on inhale.'],
  },
  {
    id: exerciseId('heel-slide'),
    name: 'Heel Slide',
    summary: 'Low-load core and pelvic control drill for limb movement without extension.',
    shortInstruction: 'Slide one heel away slowly while your pelvis stays quiet, then return with control.',
    modality: 'mobility',
    goals: ['pelvic_floor', 'hyperlordosis', 'core_strength'],
    capabilities: ['core', 'pelvic_control', 'posture'],
    equipment: { required: ['floor_mat'] },
    muscleGroups: { primary: ['core'], secondary: ['hip_flexors', 'pelvic_floor'] },
    measurements: ['reps'],
    risk: { level: 'low' },
    instructions: ['Lie on your back with knees bent.', 'Slide one heel away slowly.', 'Return without the pelvis tipping.'],
    commonMistakes: ['Letting the pelvis tip.', 'Sliding farther than you can control.', 'Holding the breath.'],
    coachingCues: ['Quiet pelvis.', 'Exhale as the leg moves.', 'Small range is fine.'],
  },
  {
    id: exerciseId('incline-treadmill-walk'),
    name: 'Incline Treadmill Walk',
    summary: 'Low-impact endurance work for aerobic capacity and hiking preparation.',
    shortInstruction: 'Set a moderate incline and walk at a sustainable pace with relaxed posture.',
    modality: 'cardio',
    goals: ['endurance', 'hiking', 'gto_gold'],
    capabilities: ['endurance', 'recovery'],
    equipment: { required: ['treadmill'] },
    muscleGroups: { primary: ['calves', 'glutes'], secondary: ['quads', 'hamstrings'] },
    measurements: ['time', 'distance'],
    media: { kind: 'gif', path: '../gifs/hike-prep.gif', alt: 'Incline walking and hiking prep demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low', notes: ['Use an incline and pace that allow steady nasal or conversational breathing.'] },
    instructions: ['Set a moderate incline.', 'Walk at a sustainable pace.', 'Cool down gradually.'],
    commonMistakes: ['Holding the rails heavily.', 'Choosing an incline that breaks posture.', 'Starting too fast.'],
    coachingCues: ['Tall posture.', 'Short quick steps.', 'Relax shoulders.'],
  },
  {
    id: exerciseId('zone-2-walk'),
    name: 'Zone 2 Walk',
    summary: 'Easy aerobic session for endurance and recovery base building.',
    shortInstruction: 'Walk at an easy conversational pace and finish feeling better than when you started.',
    modality: 'cardio',
    goals: ['endurance', 'relief'],
    capabilities: ['endurance', 'recovery'],
    equipment: { required: ['outdoor'] },
    muscleGroups: { primary: ['calves', 'glutes'], secondary: ['quads', 'hamstrings'] },
    measurements: ['time', 'distance'],
    media: { kind: 'gif', path: '../gifs/cardio.gif', alt: 'Easy cardio walking demonstration', source: 'Legacy app GIF' },
    risk: { level: 'low' },
    instructions: ['Choose an easy route.', 'Walk at a pace you can maintain comfortably.', 'Finish feeling better than when you started.'],
    commonMistakes: ['Turning the walk into a hard workout.', 'Ignoring breathing and posture.', 'Skipping the easy cool-down.'],
    coachingCues: ['Nasal or conversational pace.', 'Light arms.', 'Even stride.'],
  },
  {
    id: exerciseId('kettlebell-swing'),
    name: 'Kettlebell Swing',
    summary: 'Dynamic hinge for power, conditioning, and posterior-chain capacity.',
    shortInstruction: 'Hike the weight back, snap the hips forward, and let the weight float from the hinge.',
    modality: 'strength',
    goals: ['gto_gold', 'endurance'],
    capabilities: ['strength', 'endurance'],
    equipment: { required: ['dumbbells'] },
    muscleGroups: { primary: ['glutes', 'hamstrings'], secondary: ['core', 'back'] },
    measurements: ['reps', 'load'],
    media: { kind: 'gif', path: '../gifs/kettlebell-swing.gif', alt: 'Kettlebell swing demonstration', source: 'Legacy app GIF' },
    risk: {
      level: 'high',
      notes: ['Use only after hinge mechanics are reliable.'],
      contraindications: ['Avoid if ballistic hinging irritates the back or pelvic floor symptoms.'],
    },
    instructions: ['Hike the weight back between the hips.', 'Snap hips forward to float the weight.', 'Let the weight return into the hinge.'],
    commonMistakes: ['Squatting the swing.', 'Lifting with the arms.', 'Leaning back at lockout.'],
    coachingCues: ['Hinge, do not squat.', 'Arms are hooks.', 'Finish tall without leaning back.'],
  },
] as const;

export type Project45Exercise = Exercise;
