import type { Exercise } from './exercise.types';

export const exerciseCatalog: Exercise[] = [
  {
    id: 'pelvic-breathing',
    name: 'Диафрагмальное дыхание и расслабление тазового дна',
    englishName: 'Diaphragmatic Breathing',
    summary: 'Базовое упражнение для контроля дыхания, расслабления и восстановления.',
    goals: ['pelvic_floor', 'hyperlordosis'],
    capabilities: ['pelvic_control', 'recovery', 'posture'],
    equipment: ['floor_mat'],
    muscleGroups: ['core', 'pelvic_floor'],
    risk: 'low',
    instructions: ['Ляг на спину.', 'Вдыхай животом и нижними ребрами.', 'На вдохе расслабляй тазовое дно.', 'Не зажимай ягодицы.'],
    coachingCues: ['Дыхание без усилия.', 'Расслабление так же важно, как сокращение.'],
  },
  {
    id: 'slow-kegel',
    name: 'Кегель медленный',
    englishName: 'Slow Kegel',
    summary: 'Контрольное сокращение мышц тазового дна.',
    goals: ['pelvic_floor'],
    capabilities: ['pelvic_control'],
    equipment: ['bodyweight'],
    muscleGroups: ['pelvic_floor'],
    risk: 'low',
    instructions: ['Сожми мышцы тазового дна.', 'Удерживай 5–10 секунд.', 'Полностью расслабься.', 'Не задерживай дыхание.'],
    coachingCues: ['Не напрягай ягодицы и пресс.', 'Качество важнее количества.'],
  },
  {
    id: 'pelvic-tilt',
    name: 'Подкручивание таза лёжа',
    englishName: 'Posterior Pelvic Tilt',
    summary: 'Базовый контроль положения таза при гиперлордозе.',
    goals: ['hyperlordosis', 'core_strength'],
    capabilities: ['posture', 'core'],
    equipment: ['floor_mat'],
    muscleGroups: ['core', 'glutes'],
    risk: 'low',
    instructions: ['Ляг на спину, ноги согнуты.', 'Подкрути таз.', 'Прижми поясницу к полу.', 'Вернись в нейтральное положение.'],
    coachingCues: ['Двигай тазом, не плечами.', 'Без рывков.'],
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Растяжка сгибателей бедра',
    englishName: 'Hip Flexor Stretch',
    summary: 'Снижает тягу таза вперёд при гиперлордозе.',
    goals: ['hyperlordosis', 'hiking'],
    capabilities: ['mobility', 'posture'],
    equipment: ['floor_mat'],
    muscleGroups: ['hip_flexors', 'quads'],
    risk: 'low',
    instructions: ['Встань в выпад на колено.', 'Подкрути таз.', 'Мягко подай таз вперёд.', 'Держи 30–60 секунд.'],
    coachingCues: ['Не прогибай поясницу.', 'Натяжение спереди бедра — нормально.'],
  },
  {
    id: 'glute-bridge',
    name: 'Ягодичный мостик',
    englishName: 'Glute Bridge',
    summary: 'Ягодицы, таз, поясница, поддержка гиперлордоза и тазового дна.',
    goals: ['hyperlordosis', 'pelvic_floor', 'hiking'],
    capabilities: ['strength', 'posture', 'pelvic_control'],
    equipment: ['floor_mat', 'dumbbells'],
    muscleGroups: ['glutes', 'core', 'pelvic_floor'],
    risk: 'low',
    instructions: ['Ляг на спину, ноги согнуты.', 'Подними таз за счёт ягодиц.', 'Пауза сверху.', 'Опускайся контролируемо.'],
    coachingCues: ['Не толкай поясницей.', 'Рёбра вниз, таз подкручен.'],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    englishName: 'Dead Bug',
    summary: 'Глубокий кор без перегруза поясницы.',
    goals: ['core_strength', 'hyperlordosis'],
    capabilities: ['core', 'posture'],
    equipment: ['floor_mat'],
    muscleGroups: ['core'],
    risk: 'low',
    instructions: ['Ляг на спину.', 'Поясница прижата.', 'Опусти противоположные руку и ногу.', 'Вернись и повтори.'],
    coachingCues: ['Поясница не отрывается.', 'Медленно.'],
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    englishName: 'Bird Dog',
    summary: 'Стабилизация корпуса, таза и поясницы.',
    goals: ['core_strength', 'hyperlordosis'],
    capabilities: ['core', 'posture'],
    equipment: ['floor_mat'],
    muscleGroups: ['core', 'glutes', 'back'],
    risk: 'low',
    instructions: ['Встань на четвереньки.', 'Выпрями противоположные руку и ногу.', 'Удержи таз ровно.', 'Вернись и повтори.'],
    coachingCues: ['Не разворачивай таз.', 'Длина, а не высота.'],
  },
  {
    id: 'ab-wheel-knees',
    name: 'Ролик с коленей',
    englishName: 'Ab Wheel From Knees',
    summary: 'Сильный кор и рельеф, но только без провала поясницы.',
    goals: ['core_strength', 'relief'],
    capabilities: ['core', 'strength'],
    equipment: ['ab_wheel', 'floor_mat'],
    muscleGroups: ['core', 'shoulders'],
    risk: 'medium',
    instructions: ['Встань на колени.', 'Подкрути таз.', 'Выкатись на короткую амплитуду.', 'Вернись без прогиба в пояснице.'],
    coachingCues: ['Рёбра вниз.', 'Если поясница провисает — амплитуда слишком большая.'],
    regressions: ['dead-bug', 'plank'],
  },
  {
    id: 'push-up',
    name: 'Отжимания ГТО',
    englishName: 'Push-Up',
    summary: 'Норматив ГТО, грудь, плечи, трицепс и кор.',
    goals: ['gto_gold', 'relief', 'core_strength'],
    capabilities: ['strength', 'core'],
    equipment: ['bodyweight'],
    muscleGroups: ['chest', 'shoulders', 'arms', 'core'],
    risk: 'low',
    instructions: ['Тело одной линией.', 'Опустись контролируемо.', 'Локти примерно 45 градусов.', 'Выжми вверх.'],
    coachingCues: ['Не провисай поясницей.', 'ГТО цель: 40–50 с запасом.'],
  },
  {
    id: 'pull-up',
    name: 'Подтягивания',
    englishName: 'Pull-Up',
    summary: 'Ключевой норматив ГТО и база для скалодрома.',
    goals: ['gto_gold', 'climbing', 'relief'],
    capabilities: ['strength', 'grip'],
    equipment: ['pullup_bar'],
    muscleGroups: ['back', 'arms', 'core'],
    risk: 'medium',
    instructions: ['Вис полным хватом.', 'Лопатки вниз.', 'Подтянись до подбородка над перекладиной.', 'Опускайся контролируемо.'],
    coachingCues: ['Не до отказа каждый день.', 'Цель: 10–12 уверенно.'],
    substitutions: ['lat-pulldown'],
  },
  {
    id: 'lat-pulldown',
    name: 'Тяга верхнего блока',
    englishName: 'Lat Pulldown',
    summary: 'Замена/поддержка подтягиваний.',
    goals: ['gto_gold', 'climbing', 'relief'],
    capabilities: ['strength', 'grip'],
    equipment: ['lat_pulldown'],
    muscleGroups: ['back', 'arms'],
    risk: 'low',
    instructions: ['Сядь устойчиво.', 'Потяни рукоять к груди.', 'Лопатки вниз.', 'Верни контролируемо.'],
    coachingCues: ['Тяни локтями.', 'Не раскачивайся.'],
  },
  {
    id: 'run-intervals-400',
    name: 'Беговые интервалы 400 м',
    englishName: '400m Running Intervals',
    summary: 'Главный инструмент для 2 км за 10 минут.',
    goals: ['gto_gold', 'endurance'],
    capabilities: ['speed', 'endurance'],
    equipment: ['treadmill', 'outdoor'],
    muscleGroups: ['quads', 'hamstrings', 'calves', 'glutes'],
    risk: 'medium',
    instructions: ['Разомнись 10 минут.', 'Беги 400 м быстро.', 'Отдыхай 2 минуты.', 'Повтори 4–6 раз.'],
    coachingCues: ['Не стартуй слишком быстро.', 'Цель: постепенно выйти на 12 км/ч и выше.'],
  },
  {
    id: 'gto-abs',
    name: 'Поднимание туловища ГТО',
    englishName: 'GTO Sit-Up Test',
    summary: 'Норматив ГТО на пресс за 1 минуту.',
    goals: ['gto_gold', 'core_strength'],
    capabilities: ['core'],
    equipment: ['floor_mat'],
    muscleGroups: ['core'],
    risk: 'low',
    instructions: ['Ляг на спину.', 'Ноги согнуты.', 'Поднимай туловище по правилам теста.', 'Работай 60 секунд.'],
    coachingCues: ['Цель: 30–35 за минуту с запасом.'],
  },
  {
    id: 'sit-and-reach',
    name: 'Наклон вперёд ГТО',
    englishName: 'Sit and Reach',
    summary: 'Гибкость задней поверхности бедра и поясницы для ГТО.',
    goals: ['gto_gold', 'hyperlordosis'],
    capabilities: ['mobility'],
    equipment: ['floor_mat', 'gym_bench'],
    muscleGroups: ['hamstrings', 'calves', 'back'],
    risk: 'low',
    instructions: ['Ноги прямые.', 'Наклоняйся плавно.', 'Без рывков.', 'Дыши спокойно.'],
    coachingCues: ['Не пружинь.', 'Работай после тренировки или вечером.'],
  },
  {
    id: 'incline-walk',
    name: 'Ходьба на дорожке с наклоном',
    englishName: 'Incline Walk',
    summary: 'База выносливости для хайков и восстановления.',
    goals: ['endurance', 'hiking', 'relief'],
    capabilities: ['endurance', 'recovery'],
    equipment: ['treadmill'],
    muscleGroups: ['calves', 'glutes', 'hamstrings'],
    risk: 'low',
    instructions: ['Поставь наклон.', 'Иди 30–60 минут.', 'Дыши тяжело, но контролируемо.', 'После растяжка.'],
    coachingCues: ['Можно говорить короткими фразами — темп нормальный.'],
  },
];

export const exerciseById = new Map(exerciseCatalog.map((exercise) => [exercise.id, exercise]));
